trigger:
  - master
  - azure-pipeline
  - x64

jobs:
  - job: Windows_release
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/OCaml64.exe" -O "build\OCaml64.exe"
        displayName: 'Download OCaml'
      - script: |
          build\OCaml64.exe /S
        displayName: 'Install OCaml'
      - script: |
          C:\Ocaml64\bin\bash -l -c "opam install --yes depext depext-cygwinports; opam depext conf-gmp.1; opam install --yes menhir zarith ocamlgraph ppx_tools cppo num"
          C:\Ocaml64\bin\bash -l -c "wget https://bootstrap.pypa.io/get-pip.py ; python get-pip.py"
        displayName: 'Install dependencies'
      - script: |
          C:\Ocaml64\bin\bash -l -c 'cd $(cygpath "$BUILD_SOURCESDIRECTORY"); make windist PYTHON=python; echo "##vso[task.setvariable variable=distdir]bincat-win-$(git describe --dirty)"'
        displayName: 'Build BinCAT for Windows'
      - task: PublishBuildArtifacts@1
        displayName: Publish BinCAT for Windows installer
        continueOnError: false
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/$(distdir)
          artifactName: $(distdir)
  - job: Linux_release_and_tests
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: docker build -t "bincat:$BUILD_SOURCEVERSION" --build-arg "SOURCE_BRANCH=$BUILD_SOURCEVERSION" "$BUILD_SOURCESDIRECTORY/docker/" -f "$BUILD_SOURCESDIRECTORY/docker/Dockerfile.runtests"
        displayName: 'Build docker image'
      - script: docker run -v /tmp/linux-release:/install/bincat/release -e AZURE_BUILD=true -w /install/bincat "bincat:$BUILD_SOURCEVERSION" bash -c 'make lindist; echo "##vso[task.setvariable variable=distdir]bincat-bin-$(git describe --dirty)"; cp -R bincat-bin-* release/'
        displayName: 'Build Linux release'
      - task: PublishBuildArtifacts@1
        displayName: Publish BinCAT for Linux installer
        continueOnError: false
        inputs:
          pathtoPublish: /tmp/linux-release/$(distdir)
          artifactName: $(distdir)
      - script: docker run -v /tmp/test-results:/install/bincat/test-results -w /install/bincat/test "bincat:$BUILD_SOURCEVERSION" bash -c 'python2 -m pytest -n auto --coverage smoke -k "not repne" --junitxml=/install/bincat/test-results/pytest_report.xml || true'
        displayName: 'Run tests'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: /tmp/test-results/pytest_report.xml
